apiVersion: v1
kind: Service
metadata:
  name: rag-service
spec:
  type: NodePort
  selector:
    app: rag-app
  ports:
    - name: frontend
      port: 80
      targetPort: 8501
      nodePort: 30007

    - name: backend
      port: 8000
      targetPort: 8000